default: &default
  encoding: unicode
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: postgres
  username: postgres
  password: senha123

development:
  <<: *default
  database: smart_recycle_development

test:
  <<: *default
  database: smart_recycle_test

production:
  <<: *default
  database: smart_recycle_production
